apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "elastic-curator.fullname" . }}-config
  labels:
    app: {{ template "elastic-curator.name" . }}
    chart: {{ template "elastic-curator.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  action_file.yml: |-
    ---
    actions:
      1:
        action: delete_indices
        description: >-
           Delete indices older than {{ .Values.indicesAge }} days (based on index name), for {{ .Values.indicesName }}
           prefixed indices. Ignore the error if the filter does not result in an
           actionable list of indices (ignore_empty_list) and exit cleanly.
        options:
          timeout_override:
          continue_if_exception: False
          disable_action: False
          ignore_empty_list: True
        filters:
        - filtertype: pattern
          kind: prefix
          value: {{ .Values.indicesName }}
        - filtertype: age
          source: name
          direction: older
          timestring: '%Y.%m.%d'
          unit: days
          unit_count: {{ .Values.indicesAge }}
  config.yml: |-
    ---
    # not a Python "NoneType"
    client:
      hosts:
        - {{ .Values.elasticsearch.host }}
      port: {{ .Values.elasticsearch.port }}
      url_prefix:
      use_ssl: False
      certificate:
      client_cert:
      client_key:
      ssl_no_validate: False
      http_auth:
      timeout: 30
      master_only: False
    logging:
      loglevel: INFO
      logfile:
      logformat: default
      blacklist: ['elasticsearch', 'urllib3']